etcd:
  image: rancher/etcd:v2.3.7-6
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: data
  environment:
    RANCHER_DEBUG: '${DEBUG}'
  volumes_from:
  - etcd-data

etcd-data:
  image: busybox
  command: /bin/true
  net: none
  volumes:
  - /data
  labels:
    io.rancher.container.start_once: 'true'


arken:
  image: arken/arken:latest
  links:
    - etcd:etcd
  ports:
    - "8888:8888"
  environment:
    DRIVER: rancher
    ETCDADDRESS: http://etcd:2379/
    RANCHER_HOST: ${RANCHER_HOST}
    RANCHER_ACCESSKEY: ${RANCHER_ACCESSKEY}
    RANCHER_SECRETKEY: ${RANCHER_SECRETKEY}
gogeta:
  image: arken/gogeta:v2
  links:
    - etcd:etcd
  ports:
    - "80:7777"
  labels:
    io.rancher.scheduler.global: 'true'
